data:
  pretrain:
    dataset: PretrainObjectModuleDataset
    dataset_fn: out/datasets/pretrain/nominal_0.pkl.gzip
  train:
    dataset: ToolRotateDataset
    dataset_dir: out/datasets/combine_train_proc/
  test:
    dataset: ToolDataset
    dataset_dir: out/datasets/combine_test_proc/
    partial_pcd_idx: [ [ 3, 4, 5 ] ]
training:
  out_dir: out/models/model_v3/
  learning_rate: 0.0001
  epochs: 200
  update_object_code: false
  epochs_per_save: 10
  epochs_per_validation: 100
  load_pretrain:
    freeze_object_module_weights: true
  loss_weights:
    sdf_loss: 1.0
    normals_loss: 0.01
    embedding_loss: 1e-3
    def_loss: 1.0
    contact_loss: 0.1
    reg_loss: 1e-6
    chamfer_loss: 0.01
pretraining:
  out_dir: out/models/pretrain_v4/
  learning_rate: 0.00001
  epochs: 50000
  epochs_per_save: 1000
  loss_weights:
    sdf_loss: 1.0
    normals_loss: 0.01
    reg_loss: 1e-6
    embedding_loss: 1e-6
method: neural_contact_field
model:
  method: neural_contact_field
  z_object_size: 6
  z_deform_size: 16
  z_wrench_size: 16