data:
  pretrain:
    dataset: PretrainObjectModuleDataset
    dataset_fn: out/datasets/sim_1_20_23_v1/nominal_0.pkl.gzip
  train:
    dataset: ToolDataset
    dataset_dir: out/datasets/sim_1_20_23_v1/
training:
  out_dir: out/models/example_b1_dummy
  learning_rate: 0.0001
  betas: (.9, .999)
  weight_decay: 0
  epochs: 10000
  epochs_per_validation: 100
  update_object_code: false
  epochs_per_save: 100
  load_pretrain:
    freeze_object_module_weights: true
  loss_weights:
    sdf_loss: 1.0
    normals_loss: 0.01
    embedding_loss: 1e-3
    def_loss: 1.0
    contact_loss: 0.1
    reg_loss: 1e-6
    chamfer_loss: 0.01
pretraining:
  out_dir: out/models/example_b1
  learning_rate: 0.00001
  epochs: -1
  epochs_per_save: 1000
  loss_weights:
    sdf_loss: 1.0
    normals_loss: 0.01
    reg_loss: 1e-6
    embedding_loss: 1e-6
method: explicit_baseline
model:
  method: explicit_baseline
  z_object_size: 6
  z_deform_size: 6
  z_wrench_size: 6
