data:
  pretrain:
    dataset: PretrainObjectModuleDataset
    dataset_fn: /home/markvdm/Documents/IsaacGym/ncf_envs/out/sim_12_6_22/nominal_0.pkl.gzip
  train:
    dataset: ToolDataset
    dataset_dir: /home/markvdm/Documents/IsaacGym/ncf_envs/out/sim_12_6_22/
training:
  out_dir: out/models/ncf_v1/
  learning_rate: 0.0001
  epochs: 100000
  loss_weights:
    sdf_loss: 1.0
    embed_loss: 1.0e-8
    def_loss: 1.0e-8
    contact_loss: 0.1
    force_loss: 1.0
pretraining:
  out_dir: out/models/ncf_v1/
  learning_rate: 0.0001
  epochs: 10000
  loss_weights:
    sdf_loss: 6e6
    normals_loss: 5e1
    reg_loss: 1e2
    embedding_loss: 1e2
method: neural_contact_field
model:
  method: neural_contact_field
  z_object_size: 6
  z_deform_size: 12