data:
  dataset: ToolDataset
  dataset_dir: /home/markvdm/Documents/IsaacGym/ncf_envs/out/test_10_26_22
training:
  pretrain_file: out/models/pretrain_object_module_v2/model.pt
  out_dir: out/models/single_tool_ncf_v4/
  learning_rate: 0.0001
  print_every: 100
  epochs: 100000
  min_epochs: 100
  batch_size: 2048
  shuffle: true
  loss_weights:
    sdf_loss: 1.0
    embed_loss: 1.0e-8
    def_loss: 1.0e-8
    contact_loss: 0.1
    force_loss: 1.0
method: single_tool_neural_contact_field
model:
  method: single_tool_neural_contact_field
  z: 64
  forward_deformation: False