data:
  dataset: ToolDataset
  dataset_dir: /home/markvdm/Documents/IsaacGym/ncf_envs/out/test_10_26_22
training:
  out_dir: out/models/single_tool_ncf_v1/
  learning_rate: 0.0001
  print_every: 100
  epochs: 2000
  min_epochs: 100
  batch_size: 256
  shuffle: true
method: single_tool_neural_contact_field
model:
  method: single_tool_neural_contact_field
  z: 64
  forward_deformation: False