data:
  pretrain:
    dataset: PretrainObjectModuleDataset
    dataset_fn: /home/markvdm/Documents/IsaacGym/ncf_envs/out/sim_12_6_22/nominal_0.pkl.gzip
  train:
    dataset: ToolDataset
    dataset_dir: /home/markvdm/Documents/IsaacGym/ncf_envs/out/sim_12_6_22_single/
training:
  out_dir: out/models/pretrain_tests/ncf_v6/
  learning_rate: 0.0001
  epochs: 50000
  update_object_code: false
  freeze_pretrain_weights: true
  epochs_per_save: 1000
  loss_weights:
    sdf_loss: 1.0
    normals_loss: 0.0
    embedding_loss: 1e-3
    def_loss: 1e-8
    contact_loss: 0.0
    reg_loss: 1e-8
pretraining:
  out_dir: out/models/pretrain_tests/ncf_v6/
  learning_rate: 0.000001
  epochs: 50000
  epochs_per_save: 1000
  loss_weights:
    sdf_loss: 1.0
    normals_loss: 0.0
    reg_loss: 1e-8
    embedding_loss: 1e-8
method: neural_contact_field
model:
  method: neural_contact_field
  z_object_size: 6
  z_deform_size: 12