data:
  pretrain:
    dataset: PretrainObjectModuleDataset
    dataset_fn: /home/markvdm/Documents/IsaacGym/ncf_envs/out/sim_12_6_22/nominal_0.pkl.gzip
  train:
    dataset: ToolDataset
    dataset_dir: /home/markvdm/Documents/IsaacGym/ncf_envs/out/sim_1_20_23_v1/
training:
  out_dir: out/models/wrench_v2_tests/forward_def_v1/
  learning_rate: 0.0001
  epochs: 10000
  update_object_code: false
  epochs_per_save: 100
  epochs_per_validation: 100
  load_pretrain:
    freeze_object_module_weights: true
  loss_weights:
    sdf_loss: 1.0
    normals_loss: 0.01
    embedding_loss: 1e-3
    def_loss: 1.0
    contact_loss: 0.1
    reg_loss: 1e-6
    chamfer_loss: 0.01
pretraining:
  out_dir: out/models/pretrain_tests/test_4/
  learning_rate: 0.00001
  epochs: 50000
  epochs_per_save: 1000
  loss_weights:
    sdf_loss: 1.0
    normals_loss: 0.01
    reg_loss: 1e-6
    embedding_loss: 1e-6
method: neural_contact_field
model:
  method: neural_contact_field
  forward_deformation_input: true
  z_object_size: 6
  z_deform_size: 32
  z_wrench_size: 32