data:
  train:
    dataset: ToolRotateDataset
    dataset_dir: /home/markvdm/Documents/IsaacGym/ncf_envs/out/primitives/rebuttals/combine_train_proc/
training:
  out_dir: /home/markvdm/Documents/NCF/neural_contact_fields/out/models/undcf/model_v1/
  learning_rate: 0.0001
  epochs: 200
  epochs_per_save: 10
  loss_weights:
    sdf_loss: 1.0
    contact_loss: 0.1
    reg_loss: 1e-6
method: undcf
model:
  method: neural_contact_field
  z_deform_size: 16
  z_wrench_size: 16